### ISSUE TITLE
No download option when extension is available but outdated

### ISSUE THREAD

**Issue by Skeeve** [GeopJr/MarketVSX#1]
E.g. "Project Manager". Current version is 12.7, in open vsx it's 12.0 from two years back.

Could you show the download option every time? Or aybe only if the versions differ?

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Could you show me a screenshot of how it looks for you? The extension doesn't do any version checking, it just checks if the extension exists on open-vsx, else shows a generic download button that downloads the .vsix from marketplace. Here's how it looks for me:

![Screenshot of the marketplace page for project manager where there's a button next to the name with the label "open-vsx"](https://user-images.githubusercontent.com/18014039/219676882-a4f1aee0-6976-46e2-bb63-262293eb8996.png)

**Comment by Skeeve** [comment]
This is how it looks to me.

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/725404/219772135-295b7de9-7abb-406c-8407-21a5e90f9bba.png">

BTW: I cannot run the `ext install …` on my Mac VSCodium.

**Comment by Skeeve** [comment]
P.S. I'm using Vivaldi, a Chrome-based Browser. But there is no difference if I install the extension in Chrome.

**Comment by GeopJr** [comment]
Oh I see, I misunderstood the bug.

So you want to download the latest version and **not** the one on open-vsx?

I haven't added a static button for that, since all it does is click the already existing button on the marketplace:

![](https://user-images.githubusercontent.com/18014039/219779583-4cbb824e-83c9-4ae9-90d5-5660adc2785a.png)

It will download a .vsix file which you can install manually from here:
![](https://user-images.githubusercontent.com/18014039/219780173-9ad6bc75-1097-4774-9597-1eabf19b9cbb.png)

Keep in mind that it **won't** auto-update.

**Comment by Skeeve** [comment]
Thanks for pointing me to the correct way to download and install. Seems it was too obvious for me to understand it ;)

Do I understand correctly that I found and reported a bug?

If so, I will happily test when you fixed it.

**Comment by GeopJr** [comment]
Glad you got it solved!

It's not really a bug but a feature request - adding a static download button, but since the marketplace already has one, I'd say I probably shouldn't add it (unless there are other reasons you might need it).
